import re
from aoeData import *
# Parses user input into a readable structure that program can figure out what to do with
civ_names = [
  "(A|a)ztecs",
  "(B|b)engalis",
  "(B|b)erbers",
  "(B|b)ohemians",
  "(B|b)ritons",
  "(B|b)ulgarians",
  "(B|b)urgundians",
  "(B|b)urmese",
  "(B|b)yzantines",
  "(C|c)elts",
  "(C|c)hinese",
  "(C|c)umans",
  "(D|d)ravidians",
  "(E|e)thiopians",
  "(F|f)ranks",
  "(G|g)oths",
  "(G|g)urjaras",
  "(H|h)industanis",
  "(H|h)uns",
  "(I|i)ncas",
  "(I|i)talians",
  "(J|j)apanese",
  "(K|k)hmer",
  "(K|k)oreans",
  "(L|l)ithuanians",
  "(M|m)agyars",
  "(M|m)alay",
  "(M|m)alians",
  "(M|m)ayans",
  "(M|m)ongols",
  "(P|p)ersians",
  "(P|p)oles",
  "(P|p)ortuguese",
  "(S|s)aracens",
  "(S|s)icilians",
  "(S|s)lavs",
  "(S|s)panish",
  "(T|t)atars",
  "(T|t)eutons",
  "(T|t)urks",
  "(V|v)ietnamese",
  "(V|v)ikings",
]

synonyms = {
  "camel": "camel rider",
  "camels": "camel rider",
  "heavy camel": "heavy camel rider",
  "heavy camels": "heavy camel rider",
  "imperial camel": "imperial camel rider",
  "imperial camels": "imperial camel rider",
  "crossbow": "crossbowman",
  "crossbows": "crossbowman",
  "arbalest": "arbesester",
  "arbalests": "arbesester",
  "hca": "Heavy Cavalry Archer",
  "bbc": "Bombard Cannon",
  "so": "siege onager",
  "ram": "battering ram",
  "rams": "battering ram",
  "mango": "mangonel",
  "mangos": "mangonel",
  "janis": "janissary",
  "shotel": "shotel warrior",
  "shotels": "shotel warrior",
  "elite shotel": "elite shotel warrior",
  "elite shotels": "elite shotel warrior",
  "karambit": "karambit warrior",
  "karambits": "karambit warrior",
  "elite karambit": "elite karambit warrior",
  "elite karambits": "elite karambit warrior",
  "fire": "fire ship",
  "fires": "fire ship",
  "fast fire": "fast fire ship",
  "fast fires": "fast fire ship",
  "demo": "demolition ship",
  "demos": "demolition ship",
  "transport": "transport ship",
  "transports": "transport ship",
  "rattan": "rattan archer",
  "rattans": "rattan archer",
  "rattan": "rattan archer",
  "elite rattan": "elite rattan archer",
  "elite rattans": "elite rattan archer",
  "palisade": "palisade wall",
  "palisades": "palisade wall",
  "wall": "stone wall",
  "walls": "stone wall",
  "scout": "scout cavalry",
  "scouts": "scout cavalry",
  "light cav": "light cavalry",
  "light cavs": "light cavalry",
  "urumi": "urumi swordsman",
  "urumis": "urumi swordsman",
  "elite urumi": "elite urumi swordsman",
  "elite urumis": "elite urumi swordsman",
  "spear": "spearman",
  "spears": "spearman",
  "pike": "pikeman",
  "pikes": "pikeman",
  "halb": "halberdier",
  "halbs": "halberdier",
  "steppies": "steppe lancer",
  "elite steppies": "elite steppe lancers",
  "chakram": "chakram thrower",
  "chakrams": "chakram thrower",
  "elite chakram": "elite chakram thrower",
  "elite chakrams": "elite chakram thrower",
  "shrivamsha": "shrivamsha rider",
  "shrivamshas": "shrivamsha rider",
  "elite shrivamsha": "elite shrivamsha rider",
  "elite shrivamshas": "elite shrivamsha rider",
  "axeman": "throwing axeman",
  "axemen": "throwing axeman",
  "elite axeman": "elite throwing axeman",
  "elite axemen": "elite throwing axeman",
  "woad": "woad raider",
  "woads": "woad raider",
  "woadies": "woad raider",
  "elite woad": "elite woad raider",
  "elite woads": "elite woad raider",
  "elite woadies": "elite woad raiders",
  "jaguar": "jaguar warrior",
  "jaguars": "jaguar warrior",
  "jags": "jaguar warrior",
  "elite jaguar": "elite jaguar warrior",
  "elite jaguars": "elite jaguar warrior",
  "elite jags": "elite jaguar warrior",
  "eagle": "eagle warrior",
  "eagles": "eagle warrior",
  "elite eagle": "elite eagle warrior",
  "elite eagles": "elite eagle warrior",
  "plume": "plumed archer",
  "plumes": "plumed archer",
  "elite plume": "elite plumed archer",
  "elite plumes": "elite plumed archer",
  "conq": "conquistador",
  "conqs": "conquistador",
  "elite conq": "elite conquistador",
  "elite conqs": "elite conquistador",
  "genoese": "genoese crossbowman",
  "genoese crowssbow": "genoese crossbowman",
  "elite genoese": "elite genoese crossbowman",
  "elite genoese crossbow": "elite genoese crossbowman",
  "magyar hussar": "magyar huszar",
  "magyar hussars": "magyar huszar",
  "elite magyar hussar": "elite magyar huszar",
  "elite magyar hussars": "elite magyar huszar",
  "turtle": "turtle ship",
  "turtles": "turtle ship",
  "elite turtle": "elite turtle ship",
  "elite turtles": "elite turtle ship",
  "carto": "cartography",
  "scale mail": "Scale Mail Armor",
  "chain mail": "Chain Mail Armor",
  "plate mail": "Plate Mail Armor",
  "plate barding": "Plate Barding Armor",
  "scale barding": "Scale Barding Armor",
  "chain barding": "Chain Barding Armor",
  "padded archer": "Padded Archer Armor",
  "leather archer": "Leather Archer Armor",
  "ring archer": "ring archer armor",
  "feudal": "feudal age",
  "imperial": "imperial age",
  "parthian": "parthian tactics"
}

entities_match = f'{"|".join(synonyms.keys())}|{entities_string}'
civ_name_match = "|".join(civ_names)

cost_matches = list(map(re.compile, [
  f'(H|h)ow much do(es)? (?P<subject>{entities_match}) cost',
  f'((W|w)hat do(es)? )?(?P<subject>{entities_match}) cost',
  f'((W|w)hat is )?((T|t)he )?(C|c)ost (of )?(?P<subject>{entities_match})',
]))

civ_posession_matches = list(map(re.compile, [
  f'((D|d)o(es)? )?(?P<civilization_name>{civ_name_match}) (get(s)?|have) (?P<subject>{entities_match})',
]))

info_matches = list(map(re.compile, [
  f'(W|w)hat (does )?(?P<subject>{entities_match}) do',
  f'(T|t)ell me about (?P<subject>{entities_match})',
  f'(E|e)xplain (?P<subject>{entities_match})',
  f'^(?P<subject>{entities_match})$'
]))

