import aoeData
bloodlines = aoeData.getEntityInfo('Bloodlines')
bracer = aoeData.getEntityInfo('Bracer')
ring_archer_armor = aoeData.getEntityInfo('Ring Archer Armor')
# byztanines = process.getEntityInfo('byzantines')
print('Cost Output')
aoeData.printCost(bloodlines)
aoeData.printCost(bracer)
aoeData.printCost(ring_archer_armor)
print("General Info Output:")
aoeData.processInfo(bloodlines)
aoeData.processInfo(bracer)
aoeData.processInfo(ring_archer_armor)
# process.processInfo(byztanines)

print("Posession Output")
aoeData.processPosession('Britons', "Bloodlines")
aoeData.processPosession('Britons', "Thumb Ring")
aoeData.processPosession('Britons', "Ring Archer Armor")
aoeData.processPosession('Britons', "Bracer")
# process.processPosession('Britons', "Bracerdasd")