from copy import deepcopy
import pprint
from typing import Any, List, Dict
LANGUAGE_PART_VALUES = {
    # a type of entity you are talking about
    "ENTITY_TYPE_SPECIFIER": "ENTITY_TYPE_SPECIFIER",
    # A specific age
    "AGE_SPECIFIER": "AGE_SPECIFIER",
    # A civilization
    "CIVILIZATION": "CIVILIZATION",
    # A unit, building, tech, or upgrade 
    "ENTITY": "ENTITY",
    # A attribute of a civ like techs, UUs
    "CIV_ATTRIBUTE": 'CIV_ATTRIBUTE',
    # An attribute of an entity like cost, range, HP, etc.
    "ENTITY_ATTRIBUTE": "ENTITY_ATTRIBUTE",
    # The specific type of attack/armor like melee or pierce
    "ATTACK_CLASS_SPECIFIER": "ATTACK_CLASS_SPECIFIER",
    # Refering to a civilization as a concept
    "CIVILZATION_KEYWORD": "CIVILIZATION_KEYWORD",
    "BONUS_SPECIFIER": "BONUS_SPECIFIER"
}

ENTITY_TYPES = {
  "UNIT": "UNIT",
  "TECHNOLOGY": "TECHNOLOGY",
  "BUILDING": "BUILDING",
  "UPGRADE": "UPGRADE",
}

# ---- ENTITY SPECIFIERS -----
# meta parts of speech that declare what type of entity you are talking about
ENTITY_TYPE_SPECIFIERS = [
    {
        "value": ENTITY_TYPES['BUILDING'],
        "label": 'Building',
        "aliases": [
            "building"
            "buildings",
            'builds',
        ],
        "language_part": LANGUAGE_PART_VALUES['ENTITY_TYPE_SPECIFIER']
    },
    {
        "value": ENTITY_TYPES['TECHNOLOGY'],
        "label": 'Technology',
        "aliases": [
            "technology"
            "tech",
            'technologies',
            'techs',
        ],
        "language_part": LANGUAGE_PART_VALUES['ENTITY_TYPE_SPECIFIER']
    },
    {
        "value": ENTITY_TYPES['UNIT'],
        "label": 'Unit',
        "aliases": [
            "unit"
            "units",
        ],
        "language_part": LANGUAGE_PART_VALUES['ENTITY_TYPE_SPECIFIER']
    },
    {
        "value": ENTITY_TYPES['UPGRADE'],
        "label": 'Upgrade',
        "aliases": [
            "upgrade"
            "upgrades",
            "boost",
            "boosts",
        ],
        "language_part": LANGUAGE_PART_VALUES['ENTITY_TYPE_SPECIFIER']
    },
]
# ---- AGE MODIFIERS -----
AGE_VALUES = {
    "DARK_AGE": 0,
    "FEUDAL_AGE": 1,
    "CASTLE_AGE": 2,
    "IMPERIAL_AGE": 3,
}

AGES = [
    {
        "value": AGE_VALUES["DARK_AGE"],
        "label": "Dark Age",
        "aliases": ["dark age", "dark"],
        "language_part": LANGUAGE_PART_VALUES["AGE_SPECIFIER"],
    },
    {
        "value": AGE_VALUES["FEUDAL_AGE"],
        "label": "Feudal Age",
        "aliases": ["feudal age", "feudal"],
        "language_part": LANGUAGE_PART_VALUES["AGE_SPECIFIER"],
    },
    {
        "value": AGE_VALUES["CASTLE_AGE"],
        "label": "Castle Age",
        "aliases": ["castle age", "castle"],
        "language_part": LANGUAGE_PART_VALUES["AGE_SPECIFIER"],
    },
    {
        "value": AGE_VALUES["IMPERIAL_AGE"],
        "label": "Imperial Age",
        "aliases": ["imperial age", "imperial", "imp"],
        "language_part": LANGUAGE_PART_VALUES["AGE_SPECIFIER"],
    },
]
# ---- CIVILIZATIONS -----
CIVILIZATION_VALUES = {
    "BRITONS": "10271",
    "FRANKS": "10272",
    "GOTHS": "10273",
    "TEUTONS": "10274",
    "JAPANESE": "10275",
    "CHINESE": "10276",
    "BYZANTINES": "10277",
    "PERSIANS": "10278",
    "SARACENS": "10279",
    "TURKS": "10280",
    "VIKINGS": "10281",
    "MONGOLS": "10282",
    "CELTS": "10283",
    "SPANISH": "10284",
    "AZTECS": "10285",
    "MAYA": "10286",
    "HUNS": "10287",
    "KOREANS": "10288",
    "ITALIANS": "10289",
    "HINDUSTANIS": "10290",
    "INCA": "10291",
    "MAGYARS": "10292",
    "SLAVS": "10293",
    "PORTUEGUESE": "10294",
    "ETHIOPIANS": "10295",
    "MALIANS": "10296",
    "BERBERS": "10297",
    "KHMER": "10298",
    "MALAY": "10299",
    "BURMESE": "10300",
    "VIETNAMESE": "10301",
    "BULGARIANS": "10302",
    "TATARS": "10303",
    "CUMANS": "10304",
    "LITHUANIANS": "10305",
    "BURGUNDIANS": "10306",
    "SICILIANS": "10307",
    "POLES": "10308",
    "BOHEMIANS": "10309",
    "DRAVIDIANS": "10310",
    "BENGALIS": "10311",
    "GURJARAS": "10312",
    "ROMANS": "10313",
    "WU": "42",
    "WEI": "43",
    "SHU": "44",
    "KHITANS": "45",
    "JURCHENS": "46",
    "ARMENIANS": "47",
    "GEORGIANS": "48",
}
CIVILIZATIONS: List[Dict] = [
    {
    "aliases": [
        "aztecs",
        "aztec"
    ],
    "label": "Aztecs",
    "value": CIVILIZATION_VALUES["AZTECS"],
    "language_part": LANGUAGE_PART_VALUES['CIVILIZATION']
  },
  {
    "aliases": [
        "bengalis",
        "bengali"
    ],
    "label": "Bengalis",
    "value": CIVILIZATION_VALUES["BENGALIS"],
    "language_part": LANGUAGE_PART_VALUES['CIVILIZATION'],
  },
  {
    "aliases": [
        "armenians",
        "armenia",
        "armenian",
        "arm"
    ],
    "label": "Armenians",
    "value": CIVILIZATION_VALUES["ARMENIANS"],
    "language_part": LANGUAGE_PART_VALUES['CIVILIZATION'],
  },
  {
    "aliases": [
        "berbers",
        "berber"
    ],
    "label": "Berbers",
    "value": CIVILIZATION_VALUES["BERBERS"],
    "language_part": LANGUAGE_PART_VALUES['CIVILIZATION'],
  },
]
civ_synonyms = {
    "Aztec": "aztecs",
    "aztec": "aztecs",
    "Bengali": "bengalis",
    "bengali": "bengalis",
    "Berber": "berbers",
    "berber": "berbers",
    "Bohemian": "bohemians",
    "bohemian": "bohemians",
    "Briton": "britons",
    "briton": "britons",
    "Bulgarian": "bulgarians",
    "bulgarian": "bulgarians",
    "Burgundian": "burgundians",
    "burgundian": "burgundians",
    "Burma": "burmese",
    "burma": "burmese",
    "Byzantine": "byzantines",
    "byzantine": "byzantines",
    "Celt": "celts",
    "celt": "celts",
    "China": "chinese",
    "china": "chinese",
    "Cuman": "cumans",
    "cuman": "cumans",
    "Dravidian": "dravidians",
    "dravidian": "dravidians",
    "Ethiopian": "ethiopians",
    "ethiopian": "ethiopians",
    "Frank": "franks",
    "frank": "franks",
    "Goth": "goths",
    "goth": "goths",
    "Gurjara": "Gurjaras",
    "gurjara": "gurjaras",
    "Gurjar": "Gurjaras",
    "gurjar": "gurjaras",
    "Hindustani": "Hindustanis",
    "hindustani": "hindustanis",
    "Hun": "Huns",
    "hun": "huns",
    "Inca": "Incas",
    "inca": "incas",
    "Incan": "Incas",
    "incan": "incas",
    "Italian": "Italians",
    "italian": "italians",
    "Italy": "Italians",
    "italy": "italians",
    "Japan": "Japanese",
    "japan": "japanese",
    "Korean": "Koreans",
    "korean": "koreans",
    "Korea": "Koreans",
    "korea": "koreans",
    "Lithuanian": "Lithuanians",
    "lithuanian": "lithuanians",
    "Lithuania": "Lithuanians",
    "lithuania": "lithuanians",
    "Magyar": "Magyars",
    "magyar": "magyars",
    "Malaysia": "Malay",
    "malaysia": "malay",
    "Malian": "Malians",
    "malian": "malians",
    "Mali": "Malians",
    "mali": "malians",
    "Mayan": "Mayans",
    "mayan": "mayans",
    "Maya": "Mayans",
    "maya": "mayans",
    "Mongol": "Mongols",
    "mongol": "mongols",
    "Mongolia": "Mongols",
    "mongolia": "mongols",
    "Persian": "Persians",
    "persian": "persians",
    "Persia": "Persians",
    "persia": "persians",
    "Pole": "Poles",
    "pole": "poles",
    "Poland": "Poles",
    "poland": "poles",
    "Polish": "Poles",
    "polish": "poles",
    "Portugal": "Portuguese",
    "portugal": "portuguese",
    "Saracen": "Saracens",
    "saracen": "saracens",
    "Sicilian": "Sicilians",
    "sicilian": "sicilians",
    "Sicily": "Sicilians",
    "sicily": "sicilians",
    "Slav": "Slavs",
    "slav": "slavs",
    "Slavic": "Slavs",
    "slavic": "slavs",
    "Spanish": "Spanish",
    "spanish": "spanish",
    "Spain": "Spanish",
    "spain": "spanish",
    "Spainard": "Spanish",
    "spainard": "spanish",
    "Tatar": "Tatars",
    "tatar": "tatars",
    "Teuton": "Teutons",
    "teuton": "teutons",
    "Turk": "Turks",
    "turk": "turks",
    "Turkey": "Turks",
    "turkey": "turks",
    "Turkish": "Turks",
    "turkish": "turks",
    "Vietnam": "Vietnamese",
    "vietnam": "vietnamese",
    "Viking": "Vikings",
    "viking": "vikings",
  }


# ---- ENTITIES ---
# >> ENTITIES.UNITS
UNIT_VALUES = {
    "Villager": "5606" ,
    
    "Trade Cart": "19052",

    "Spearman": "5078" ,
    "Pikeman": "5408" ,
    "Halberdier": "5409" ,
    "Militia": "5079" ,
    "Man-at-Arms": "5080" ,
    "Long Swordsman": "5081" ,
    "Two-Handed Swordsman": "5411" ,
    "Champion": "5469" ,
    "Legionary": "5054" ,

    "Skirmisher": "5088" ,
    "Elite Skirmisher": "5087" ,
    "Imperial Skirmisher": "5190" ,
    "Archer": "5083" ,
    "Crossbowman": "5084" ,
    "Arbalester": "5418" ,
    "Cavalry Archer": "5085" ,
    "Heavy Cavalry Archer": "5412" ,
    "Hand Cannoneer": "5086" ,
    "Genitour": "5137" ,
    "Elite Genitour": "5139" ,
    "Slinger": "5690" ,


    "Scout Cavalry": "5326" ,
    "Light Cavalry": "5444" ,
    "Hussar": "5661" ,
    "Winged Hussar": "5577" ,
    "Knight": "5068" ,
    "Cavalier": "5070" ,
    "Paladin": "5471" ,
    "Camel Scout": "5441" ,
    "Camel Rider": "5416" ,
    "Heavy Camel Rider": "5417" ,
    "Imperial Camel Rider": "5419" ,
    "Steppe Lancer": "5009" ,
    "Elite Steppe Lancer": "5010" ,
    "Xolotl Warrior": "5040" ,
    "Battle Elephant": "5167" ,
    "Elite Battle Elephant": "5168" ,
    "Shrivamsha Rider": "5437" ,
    "Elite Shrivamsha Rider": "5438" ,

    "Transport Ship": "5443" ,
    "Fishing Ship": "5090" ,
    "Trade Cog": "5089" ,
    "Galley": "5436" ,
    "War Galley": "5091" ,
    "Galleon": "5309" ,
    "Fire Galley": "5160" ,
    "Fire Ship": "5426" ,
    "Fast Fire Ship": "5429" ,
    "Demolition Raft": "5162" ,
    "Demolition Ship": "5424" ,
    "Heavy Demolition Ship": "5425" ,
    "Cannon Galleon": "5287" ,
    "Elite Cannon Galleon": "5573" ,
    "Dromon": "5055" ,
    "Caravel": "5132" ,
    "Elite Caravel": "5133" ,
    "Thirisadai": "5435" ,

    "Battering Ram": "5094" ,
    "Capped Ram": "5289" ,
    "Siege Ram": "5446" ,
    "Mangonel": "5095" ,
    "Onager": "5448" ,
    "Siege Onager": "5493" ,
    "Scorpion": "5096" ,
    "Heavy Scorpion": "5439" ,
    "Siege Tower": "5445" ,
    "Bombard Cannon": "5093" ,
    "Houfnice": "5579" ,
    "Flaming Camel": "5375" ,
    "Armored Elephant": "5428" ,
    "Siege Elephant": "5430" ,

    "Monk": "5099" ,
    "Missionary": "5691" ,

    "Trebuchet": "5097" ,
    "Petard": "5660" ,

    "Centurion": "5052" ,
    "Elite Centurion": "5053" ,
    "Cataphract": "5101" ,
    "Chu Ko Nu": "5102" ,
    "Mameluke": "5103" ,
    "Huskarl": "5104" ,
    "Janissary": "5105" ,
    "Longboat": "5106" ,
    "Longbowman": "5107" ,
    "Mangudai": "5108" ,
    "War Elephant": "5109" ,
    "Samurai": "5110" ,
    "Throwing Axeman": "5111" ,
    "Teutonic Knight": "5112" ,
    "Woad Raider": "5113" ,
    "Condottiero": "5114" ,
    "Organ Gun": "5129" ,
    "Elite Organ Gun": "5130" ,
    "Camel Archer": "5134" ,
    "Elite Camel Archer": "5136" ,
    "Monastery": "5138" ,
    "Gbeto": "5140" ,
    "Elite Gbeto": "5141" ,
    "Shotel Warrior": "5143" ,
    "Elite Shotel Warrior": "5145" ,
    "Ballista Elephant": "5146" ,
    "Elite Ballista Elephant": "5147" ,
    "Karambit Warrior": "5148" ,
    "Elite Karambit Warrior": "5150" ,
    "Arambai": "5151" ,
    "Elite Arambai": "5152" ,
    "Rattan Archer": "5165" ,
    "Elite Rattan Archer": "5166" ,
    "Konnik": "5288" ,
    "Elite Konnik": "5290" ,
    "Keshik": "5313" ,
    "Elite Keshik": "5314" ,
    "Kipchak": "5315" ,
    "Elite Kipchak": "5327" ,
    "Leitis": "5328" ,
    "Elite Leitis": "5329" ,
    "Urumi Swordsman": "5403" ,
    "Elite Urumi Swordsman": "5413" ,
    "Chakram Thrower": "5421" ,
    "Elite Chakram Thrower": "5427" ,
    "Ghulam": "5431" ,
    "Elite Ghulam": "5432" ,
    "Boyar": "5447" ,
    "Elite Boyar": "5449" ,
    "Elite Cataphract": "5451" ,
    "Elite Chu Ko Nu": "5452" ,
    "Elite Mameluke": "5453" ,
    "Elite Huskarl": "5454" ,
    "Elite Janissary": "5455" ,
    "Elite Longbowman": "5456" ,
    "Elite Longboat": "5457" ,
    "Elite Mangudai": "5458" ,
    "Elite War Elephant": "5459" ,
    "Elite Samurai": "5460" ,
    "Elite Throwing Axeman": "5461" ,
    "Elite Teutonic Knight": "5462" ,
    "Elite Woad Raider": "5463" ,
    "Coustillier": "5534" ,
    "Elite Coustillier": "5536" ,
    "Serjeant": "5538" ,
    "Elite Serjeant": "5540" ,
    "Flemish Militia": "5542" ,
    "Obuch": "5558" ,
    "Elite Obuch": "5559" ,
    "Hussite Wagon": "5561" ,
    "Elite Hussite Wagon": "5563" ,
    "Berserk": "5574" ,
    "Elite Berserk": "5576" ,
    "Jaguar Warrior": "5667" ,
    "Elite Jaguar Warrior": "5669" ,
    "Eagle Warrior": "5671" ,
    "Eagle Scout": "5672" ,
    "Elite Eagle Warrior": "5673" ,
    "Tarkan": "5675" ,
    "Elite Tarkan": "5677" ,
    "Elephant Archer": "5682" ,
    "Plumed Archer": "5683" ,
    "Elite Elephant Archer": "5684" ,
    "Elite Plumed Archer": "5685" ,
    "Kamayuk": "5686" ,
    "Conquistador": "5687" ,
    "Elite Kamayuk": "5688" ,
    "Elite Conquistador": "5689" ,
    "Genoese Crossbowman": "5723" ,
    "Elite Genoese Crossbowman": "5725" ,
    "War Wagon": "5727" ,
    "Magyar Huszar": "5728" ,
    "Elite War Wagon": "5729" ,
    "Elite Magyar Huszar": "5730" ,
    "Turtle Ship": "5731" ,
    "Elite Turtle Ship": "5732" ,
    "Konnik (Dismounted)": "21057",
    "Elite Konnik (Dismounted)": "21058",
    "Ratha (Melee)": "21096",
    "Elite Ratha (Melee)": "21097",
    "Ratha": "21104",
    "Elite Ratha": "21105",
}
UNITS = [
    {
        "aliases": ["arb", "arbalester", "arbalest", "arblest"],
        "label": "Arbalest",
        "value": UNIT_VALUES['Arbalester'],
        "entity_type": ENTITY_TYPES['UNIT'],
        "language_part": LANGUAGE_PART_VALUES["ENTITY"],
    },
    {
        "aliases": [
            "arambai",
        ],
        "label": "Arambai",
        "value": UNIT_VALUES['Arambai'],
        "entity_type": ENTITY_TYPES['UNIT'],
        "language_part": LANGUAGE_PART_VALUES["ENTITY"],
    },
    {
        "aliases": [
            "camels",
            "camel",
            "camel rider",
            "camel riders"
        ],
        "label": 'Camel Rider',
        "value": UNIT_VALUES['Camel Rider'],
        "entity_type": ENTITY_TYPES['UNIT'],
        "language_part": LANGUAGE_PART_VALUES["ENTITY"],
    },
    {
        "aliases": [
            "heavy camel",
            "heavy camels",
            "heavy camel rider",
            "heavy camel riders"
        ],
        "label": "Heavy Camel Rider",
        "value": UNIT_VALUES["Heavy Camel Rider"],
        "entity_type": ENTITY_TYPES['UNIT'],
        "language_part": LANGUAGE_PART_VALUES["ENTITY"],
    },
    {
        "value": UNIT_VALUES['Camel Archer'],
        "label": "Camel Archer",
        "aliases": [
            "camel archer",
            "camel archer",
            "cam archer",
            "cam arch",
        ],
        "entity_type": ENTITY_TYPES["UNIT"],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    },
    {
        "value": UNIT_VALUES['Elite Camel Archer'],
        "label": "Elite Camel Archer",
        "aliases": [
            "elite camel archer",
            "el camel archer",
            "el cam arch",
        ],
        "entity_type": ENTITY_TYPES["UNIT"],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    }
]
unit_synonyms = {
    "camel": "camel rider",
    "camels": "camel rider",
    "heavy camel": "heavy camel rider",
    "heavy camels": "heavy camel rider",
    "imperial camel": "imperial camel rider",
    "imperial camels": "imperial camel rider",
    "crossbow": "crossbowman",
    "crossbows": "crossbowman",
    "arbalest": "arbesester",
    "arbalests": "arbesester",
    "hca": "Heavy Cavalry Archer",
    "bbc": "Bombard Cannon",
    "so": "siege onager",
    "ram": "battering ram",
    "rams": "battering ram",
    "mango": "mangonel",
    "mangos": "mangonel",
    "janis": "janissary",
    "shotel": "shotel warrior",
    "shotels": "shotel warrior",
    "elite shotel": "elite shotel warrior",
    "elite shotels": "elite shotel warrior",
    "karambit": "karambit warrior",
    "karambits": "karambit warrior",
    "elite karambit": "elite karambit warrior",
    "elite karambits": "elite karambit warrior",
    "fire": "fire ship",
    "fires": "fire ship",
    "fast fire": "fast fire ship",
    "fast fires": "fast fire ship",
    "demo": "demolition ship",
    "demos": "demolition ship",
    "transport": "transport ship",
    "transports": "transport ship",
    "rattan": "rattan archer",
    "rattans": "rattan archer",
    "rattan": "rattan archer",
    "elite rattan": "elite rattan archer",
    "elite rattans": "elite rattan archer",
    "palisade": "palisade wall",
    "palisades": "palisade wall",
    "wall": "stone wall",
    "walls": "stone wall",
    "scout": "scout cavalry",
    "scouts": "scout cavalry",
    "light cav": "light cavalry",
    "light cavs": "light cavalry",
    "urumi": "urumi swordsman",
    "urumis": "urumi swordsman",
    "elite urumi": "elite urumi swordsman",
    "elite urumis": "elite urumi swordsman",
    "spear": "spearman",
    "spears": "spearman",
    "pike": "pikeman",
    "pikes": "pikeman",
    "halb": "halberdier",
    "halbs": "halberdier",
    "steppies": "steppe lancer",
    "elite steppies": "elite steppe lancers",
    "chakram": "chakram thrower",
    "chakrams": "chakram thrower",
    "elite chakram": "elite chakram thrower",
    "elite chakrams": "elite chakram thrower",
    "shrivamsha": "shrivamsha rider",
    "shrivamshas": "shrivamsha rider",
    "elite shrivamsha": "elite shrivamsha rider",
    "elite shrivamshas": "elite shrivamsha rider",
    "axeman": "throwing axeman",
    "axemen": "throwing axeman",
    "elite axeman": "elite throwing axeman",
    "elite axemen": "elite throwing axeman",
    "woad": "woad raider",
    "woads": "woad raider",
    "woadies": "woad raider",
    "elite woad": "elite woad raider",
    "elite woads": "elite woad raider",
    "elite woadies": "elite woad raiders",
    "jaguar": "jaguar warrior",
    "jaguars": "jaguar warrior",
    "jags": "jaguar warrior",
    "elite jaguar": "elite jaguar warrior",
    "elite jaguars": "elite jaguar warrior",
    "elite jags": "elite jaguar warrior",
    "eagle": "eagle warrior",
    "eagles": "eagle warrior",
    "elite eagle": "elite eagle warrior",
    "elite eagles": "elite eagle warrior",
    "plume": "plumed archer",
    "plumes": "plumed archer",
    "elite plume": "elite plumed archer",
    "elite plumes": "elite plumed archer",
    "conq": "conquistador",
    "conqs": "conquistador",
    "elite conq": "elite conquistador",
    "elite conqs": "elite conquistador",
    "genoese": "genoese crossbowman",
    "genoese crowssbow": "genoese crossbowman",
    "elite genoese": "elite genoese crossbowman",
    "elite genoese crossbow": "elite genoese crossbowman",
    "magyar hussar": "magyar huszar",
    "magyar hussars": "magyar huszar",
    "elite magyar hussar": "elite magyar huszar",
    "elite magyar hussars": "elite magyar huszar",
    "turtle": "turtle ship",
    "turtles": "turtle ship",
    "elite turtle": "elite turtle ship",
    "elite turtles": "elite turtle ship",
    "carto": "cartography",
    "scale mail": "Scale Mail Armor",
    "chain mail": "Chain Mail Armor",
    "plate mail": "Plate Mail Armor",
    "plate barding": "Plate Barding Armor",
    "scale barding": "Scale Barding Armor",
    "chain barding": "Chain Barding Armor",
    "padded archer": "Padded Archer Armor",
    "leather archer": "Leather Archer Armor",
    "ring archer": "ring archer armor",
    "feudal": "feudal age",
    "imperial": "imperial age",
    "parthian": "parthian tactics",
  }

# >> ENTITIES.TECHS
TECH_VALUES = {
    "Loom": "7022",
    "Wheelbarrow": "7211",
    "Town Watch": "7008",
    "Hand Cart": "7246",
    "Town Patrol": "7282",
    "Feudal Age": "7101",
    "Castle Age": "7102",
    "Imperial Age": "7103",

    "Horse Collar": "7014",
    "Heavy Plow": "7013",
    "Crop Rotation": "7012",

    "Guilds": "7015",
    "Banking": "7017",
    "Cartography": "7019",
    "Coinage": "7023",

    "Tracking": "7090",
    "Squires": "7210",
    "Arson": "7258",
    "Supplies": "7403",
    "Gambesons": "7450",

    "Husbandry": "7039",
    "Bloodlines": "7409",

    "Parthian Tactics": "7415",
    "Thumb Ring": "7411",

    "Gillnets": "7314",
    "Careening": "7372",
    "Dry Dock": "7373",
    "Shipwright": "7377",

    "Fervor": "7249",
    "Faith": "7045",
    "Illumination": "7220",
    "Sanctity": "7221",
    "Block Printing": "7222",
    "Redemption": "7315",
    "Atonement": "7316",
    "Theocracy": "7416",
    "Caravan": "7410",
    "Heresy": "7412",
    "Herbal Medicine": "7435",

    "Heated Shot": "7374",
    "Chemistry": "7047",
    "Masonry": "7050",
    "Architecture": "7051",
    "Treadmill Crane": "7054",
    "Guard Tower": "7186",
    "Keep": "7063",
    "Arrowslits": "7278",
    "Ballistics": "7093",
    "Fortified Wall": "7163",
    "Bombard Tower": "7320",
    "Murder Holes": "7321",


    "Gold Mining": "7055",
    "Gold Shaft Mining": "7180",
    "Stone Mining": "7276",
    "Stone Shaft Mining": "7277",

    "Double-Bit Axe": "7189",
    "Bow Saw": "7190",
    "Two-Man Saw": "7231",
    
    "Forging": "7067",
    "Iron Casting": "7068",
    "Scale Mail Armor": "7074",
    "Blast Furnace": "7075",
    "Chain Mail Armor": "7076",
    "Plate Mail Armor": "7077",
    "Plate Barding Armor": "7080",
    "Scale Barding Armor": "7081",
    "Chain Barding Armor": "7082",
    "Bodkin Arrow": "7150",
    "Bracer": "7151",
    "Fletching": "7172",
    "Padded Archer Armor": "7208",
    "Leather Archer Armor": "7209",
    "Ring Archer Armor": "7216",
    
    "Siege Engineers": "7378",
    "Conscription": "7319",
    "Sappers": "7322",
    "Hoardings": "7376",
    "Spies/Treason": "7408",

    "Kataparuto": "7059",
    "Carrack": "7250",
    "Arquebus": "7251",
    "Royal Heirs": "7252",
    "Torsion Engines": "7253",
    "Tigui": "7254",
    "Farimba": "7255",
    "Kasbah": "7256",
    "Maghrebi Camels": "7257",
    "Andean Sling": "7266",
    "Fabric Shields": "7267",
    "Druzhina": "7269",
    "Grand Trunk Road": "7270",
    "Shatagni": "7271",
    "Pavise": "7272",
    "Silk Road": "7273",
    "Recurve Bow": "7274",
    "Corvinian Army": "7275",
    "Nomads": "7280",
    "Kamandaran": "7281",
    "Ironclad": "7283",
    "Sipahi": "7285",
    "Inquisition": "7286",
    "Chivalry": "7287",
    "Tusk Swords": "7291",
    "Double Crossbow": "7292",
    "Thalassocracy": "7293",
    "Forced Levy": "7294",
    "Howdah": "7295",
    "Manipur Cavalry": "7296",
    "Chatras": "7297",
    "Paper Money": "7298",
    "Stirrups": "7307",
    "Bagains": "7308",
    "Silk Armor": "7309",
    "Timurid Siegecraft": "7310",
    "Steppe Husbandry": "7311",
    "Chieftains": "7312",
    "Greek Fire": "7313", 
    "Logistica": "7318",
    "Bearded Axe": "7324",
    "Supremacy": "7325",
    "Atlatl": "7326",
    "Warwolf": "7327",
    "Burgundian Vineyards": "7342",
    "Flemish Revolution": "7343",
    "First Crusade": "7344",
    "Hauberk": "7345",
    "Szlachta Privileges": "7348",
    "Lechitic Legacy": "7349",
    "Wagenburg Tactics": "7350",
    "Hussite Reforms": "7351",
    "Medical Corps": "7357",
    "Wootz Steel": "7358",
    "Paiks": "7359",
    "Mahayana": "7360",
    "Kshatriyas": "7361",
    "Frontier Guards": "7362",
    "Great Wall": "7368",
    "Stronghold": "7369",
    "Marauders": "7370",
    "Yasama": "7371",
    "Hul'che Javelineers": "7379",
    "Eupseong": "7380",
    "Cuman Mercenaries": "7398",
    "Hill Forts": "7399",
    "Tower Shields": "7400",
    "Yeomen": "7419",
    "El Dorado": "7420",
    "Furor Celtica": "7421",
    "Drill": "7422",
    "Mahouts": "7423",
    "Zealotry": "7424",
    "Artillery": "7425",
    "Crenellations": "7426",
    "Anarchy": "7427",
    "Atheism": "7428",
    "Garland Wars": "7429",
    "Bogsveigar": "7431",
    "Rocketry": "7432",
    "Shinkichon": "7438",
    "Perfusion": "7439",
    "Ballistas": "7444",
    "Comitatenses": "7445",
    "Counterweights": "7447",
    "Detinets": "7448",
}
TECHS = [
    {
        "value": TECH_VALUES['Anarchy'],
        'label': 'Anarchy',
        'aliases': ['anarchy'],
        "entity_type": ENTITY_TYPES["TECHNOLOGY"],
        "language_part": LANGUAGE_PART_VALUES["ENTITY"]
    },
    {
        "value": TECH_VALUES['Loom'],
        'label': 'Loom',
        'aliases': ['loom'],
        "entity_type": ENTITY_TYPES["TECHNOLOGY"],
        "language_part": LANGUAGE_PART_VALUES["ENTITY"],
    },
    {
        "value": TECH_VALUES['Forging'],
        'label': 'Forging',
        'aliases': [
            'forging',
            'forgin',
            'first melee attack upgrade',
            'first infantry attack upgrade', 
            'first cavalry attack upgrade',
            'first cavalry attack upgrade',
            'first melee attack tech',
            'first infantry attack tech',
            'first cavalry attack tech',
        ],
        "entity_type": ENTITY_TYPES["TECHNOLOGY"],
        "language_part": LANGUAGE_PART_VALUES["ENTITY"],
    },
]
# ENTITIES.UPGRADES
UPGRADE_VALUES = {
    "Elite Centurion": "5053" ,
    "Elite Organ Gun": "5130" ,
    "Elite Caravel": "5133" ,
    "Elite Camel Archer": "5136" ,
    "Elite Genitour": "5139" ,
    "Elite Gbeto": "5141" ,
    "Elite Shotel Warrior": "5145" ,
    "Elite Ballista Elephant": "5147" ,
    "Elite Karambit Warrior": "5150" ,
    "Elite Arambai": "5152" ,
    "Elite Rattan Archer": "5166" ,
    "Elite Konnik": "5290" ,
    "Elite Keshik": "5314" ,
    "Elite Kipchak": "5327" ,
    "Elite Leitis": "5329" ,
    "Elite Urumi Swordsman": "5413" ,
    "Elite Chakram Thrower": "5427" ,
    "Elite Ghulam": "5432" ,
    "Elite Boyar": "5449",
    "Elite Cataphract": "5451",
    "Elite Chu Ko Nu": "5452",
    "Elite Mameluke": "5453",
    "Elite Huskarl": "5454",
    "Elite Janissary": "5455",
    "Elite Longbowman": "5456",
    "Elite Berserk": "5576",
    "Elite Longboat": "5457",
    "Elite Mangudai": "5458",
    "Elite War Elephant": "5459",
    "Elite Samurai": "5460",
    "Elite Throwing Axeman": "5461",
    "Elite Teutonic Knight": "5462",
    "Elite Woad Raider": "5463",
    "Elite Coustillier": "5536",
    "Elite Serjeant": "5540",
    "Elite Obuch": "5559",
    "Elite Hussite Wagon": "5563",
    "Elite Jaguar Warrior": "5669",
    "Elite Tarkan": "5677",
    "Elite Elephant Archer": "5684",
    "Elite Plumed Archer": "5685",
    "Elite Kamayuk": "5688",
    "Elite Conquistador": "5689",
    "Elite Genoese Crossbowman": "5725",
    "Elite Magyar Huszar": "5730",
    "Elite War Wagon": "5729",
    "Elite Turtle Ship": "5732",
    "Elite Konnik": "21058",
    "Elite Ratha": "21097",
    
    "Light Cavalry": "5444" ,
    "Hussar": "5661",
    "Winged Hussar": "5577",
    "Cavalier": "5070" ,
    "Paladin": "5471",
    "Heavy Camel Rider": "UPGRADE_5417" ,
    "Imperial Camel Rider": "5419" ,
    "Elite Steppe Lancer": "5010" ,
    "Elite Battle Elephant": "5168" ,
    "Elite Shrivamsha Rider": "5438" ,
    # Svar
    # Heavy Hei guang Cav

    "Man-at-Arms": "5080" ,
    "Long Swordsman": "5081" ,
    "Two-Handed Swordsman": "5411" ,   
    "Champion": "5469",
    "Legionary": "5054" ,
    "Pikeman": "5408" ,
    "Halberdier": "5409" ,
    "Eagle Warrior": "5671",
    "Elite Eagle Warrior": "5673",

    "Crossbowman": "5084" ,
    "Arbalester": "5418" ,
    "Elite Skirmisher": "5087" ,
    "Imperial Skirmisher": "5190" ,
    "Heavy Cavalry Archer": "5412" ,

    "War Galley": "5091" ,
    "Galleon": "5309",
    "Elite Cannon Galleon": "5573",
    "Fast Fire Ship": "5429" ,

    "Capped Ram": "5289",
    "Siege Ram": "5446" ,
    "Onager":  "5448",
    "Siege Onager": "5493",
    "Heavy Scorpion": "5439" ,
    "Siege Elephant": "5430" ,
    "Houfnice": "5579",

    "Fortified Wall": "5204",
    "Watch Tower":"5178",
    "Keep":"7063",
}
UPGRADES = [
    {
        "value": UPGRADE_VALUES['Crossbowman'],
        "label": "Crossbowman",
        "aliases": [
            "crossbowman",
            "crowwbow",
            "crossbowmen",
            "xbow",
            "xbows",
            "first archer",
        ],
        "entity_type": ENTITY_TYPES["UPGRADE"],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    },
    {
        "value": UPGRADE_VALUES['Arbalester'],
        "label": "Arbalester",
        "aliases": [
            "arbalest",
            "arbelest",
            "arb",
            "second archer",
            "first crossbow",
            "first crossbowman",
            "first crossbowmen",
            "first xbow",
        ],
        "entity_type": ENTITY_TYPES["UPGRADE"],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    },
    {
        "value": UPGRADE_VALUES['Heavy Camel Rider'],
        "label": "Heavy Camel Rider",
        "aliases": [
            "heavy camel", 
            'heavy camel rider',
            'first camel rider',
            'first camel',
        ],
        "entity_type": ENTITY_TYPES["UPGRADE"],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    },
    {
        "value": UPGRADE_VALUES['Elite Camel Archer'],
        "label": "Elite Camel Archer",
        "aliases": [
            "elite camel archer",
            "el camel archer",
        ],
        "entity_type": ENTITY_TYPES["UPGRADE"],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    }
]
# ENTITIES.BUILDINGS
BUILDING_VALUES = {
    "Town Center": "5164",
    "House": "5344",
    "Farm": "5149",
    "Mill": "5157",
    "Folwark": "5581",
    "Lumber Camp": "5464",
    "Mining Camp": "5487",
    "Dock": "5144",
    "Fish Trap": "5495",
    "Harbor": "5249",
    "Barracks": "5135",
    "Archery Range": "5128",
    "Stable": "5171",
    "Market": "5161",
    "Blacksmith": "5131",
    "Siege Workshop": "5169",
    "Monastery": "5138",
    "University": "5176",
    "Castle": "5142",
    "Palisade Wall": "5202",
    "Stone Wall": "5203",
    "Fortified Wall": "5204",
    "Gate": "5185",
    "Palisade Gate": "5186",
    "Outpost": "5504",
    "Watch Tower": "5178",
    "Guard Tower": "5154",
    "Keep": "5155",
    "Keep": "7063",
    "Bombard Tower": "5156",
    "Donjon": "5544",
    "Krepost": "5349",
    "Feitoria": "5159",
    "Wonder": "5182",
    "Caravanserai": "5440",
}
BUILDINGS = [
    {
        "value": BUILDING_VALUES['Archery Range'],
        "label": 'Archery Range',
        "aliases": [
            'archery range',
            'range'
        ],
        "entity_type": ENTITY_TYPES['BUILDING'],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    },
    {
        "value": BUILDING_VALUES['Blacksmith'],
        "label": 'Blacksmith',
        "aliases": [
            'blacksmith',
            'bs',
            'smith',
            'blocksmith'
        ],
        "entity_type": ENTITY_TYPES['BUILDING'],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],

    },
    {
        "value": BUILDING_VALUES['Castle'],
        "label": 'Castle',
        "aliases": [
            'castle',
            'castles',
            'cast',
            'fort',
            'palace',
        ],
        "entity_type": ENTITY_TYPES['BUILDING'],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],

    },
    {
        "value": BUILDING_VALUES['Watch Tower'],
        "label": 'Watch Tower',
        "aliases": [
            'tower',
            'watch tower',
            'towers',
            'watch towers',
            'tow',
            'watch tow'
        ],
        "entity_type": ENTITY_TYPES['BUILDING'],
        "language_part": LANGUAGE_PART_VALUES['ENTITY'],
    },
]

ENTITIES = BUILDINGS + UNITS + TECHS + UPGRADES

# ------ ENTITY ATTRIBUTES -----
# what specific attribute of an entity you are refering to
ENTITY_ATTRIBUTE_VALUES = {
    "COST": "COST",
    "HIT_POINTS": "HIT_POINTS",
    "ARMOR": "ARMOR",
    "PIERCE_ARMOR": "MELEE_ARMOR",
    "MELEE_ARMOR": "MELEE_ARMOR",
    "ATTACK": "ATTACK",
    "CHARGE_ATTACK": "CHARGE_ATTACK",
    "RANGE": "RANGE",
    "MINIMUM_RANGE": "MINIMUM_RANGE",
    "MOVEMENT_SPEED": "MOVEMENT_SPEED",
    "ATTACK_SPEED": "ATTACK_SPEED",
    "FRAME_DELAY": "FRAME_DELAY",
    "ATTACK_DELAY": "ATTACK_DELAY",
    "RELOAD_TIME": "RELOAD_TIME",
    "ACCURACY": "ACCURACY",
    "HP_REGENERATION_RATE": "HP_REGENERATION_RATE",
    "LINE_OF_SIGHT": "LINE_OF_SIGHT",
    "BUILD_TIME": "BUILD_TIME",
    "CONVERSION_RESISTANCE": "CONVERSION_RESISTANCE",
    # SPECIAL ARMORS
    # BONUS ATTACKS
}

ENTITY_ATTRIBUTES = [
    {
        "value": ENTITY_ATTRIBUTE_VALUES['HIT_POINTS'],
        "label": 'Hit Points',
        "aliases": [
            "hp",
            "health",
            "hit points",
            'hits',
        ],
        "language_part": LANGUAGE_PART_VALUES['ENTITY_ATTRIBUTE']
    },
    {
        "value": ENTITY_ATTRIBUTE_VALUES['COST'],
        "label": 'Cost',
        "aliases": [
            "cost",
            'price',
            'build cost',
            'expense',
        ],
        "language_part": LANGUAGE_PART_VALUES['ENTITY_ATTRIBUTE']
    },
]
ATTACK_CLASS_SPECIFIER_VALUES = {
    'BASE_MELEE': 'BASE_MELEE',
    'BASE_PIERCE': 'BASE_PIERCE',
    'CAVALRY': 'CAVALRY',
    "INFANTRY": "INFANTRY",
    "ARCHERS": "ARCHERS",
    "WONDERS": "WONDERS",
    "SIEGE_UNITS": "SIEGE_UNITS",
    "HEAVY_WARSHIPS": "HEAVY_WARSHIPS",
    "ELEPHANT": "ELEPHANT",
    "TREES": "TREES",
    "UNIQUE_UNITS": "UNIQUE_UNITS",
    "GUNPOWDER": "GUNPOWDER",
    "MONKS": "MONKS",
    "SPEARMEN": "SPEARMEN",
    "MOUNTED_ARCHERS": "MOUNTER_ARCHERS",
    "SHOCK_INFANTRY": "SHOCK_INFANTRY",
    "CAMELS": "CAMELS",
    "ANTI_ARCHER": "ANTI_ARCHER",
    "LEITIS_ATTACK": "LEITIS_ATTACK",
    "FISHING_SHIPS": "FISHING_SHIPS",
    "MOUNTED_UNITS": "MOUNTED_UNITS",
    "Hussite Wagons and Ballista Elephants": "Hussite Wagons and Ballista Elephants",
    "Condottieri": "Condottieri",
    "MAMELUKES": "MAMELUKES",
    "HEROES": "HEROES",
    "NONE": "NONE",
    "Buildings except Fish Traps": "Buildings except Fish Traps",
    "Stone Walls, Gates, Towers, and Harbors": "Stone Walls, Gates, Towers, and Harbors",
    "Predator Animals": "Predator Animals",
    "Ships excluding Fire Ships": "Ships excluding Fire Ships",
    "Rams, Unpacked Trebuchets, and Siege Towers": "Rams, Unpacked Trebuchets, and Siege Towers",
    "Standard Buildings except Fish Traps and Wonders": "Standard Buildings except Fish Traps and Wonders",
    "Walls and Gates": "Walls and Gates",
    "Hunted Predator Animals": "Hunted Predator Animals",
    "Castles and Kreposts": "Castles and Kreposts",
}
ATTACK_CLASS_SPECIFIERS = [
    {
        "value": ATTACK_CLASS_SPECIFIER_VALUES['BASE_MELEE'],
        "label": 'Melee',
        "language_part": LANGUAGE_PART_VALUES["ATTACK_CLASS_SPECIFIER"],
        "aliases": [
            'melee',
            'mele',
            'meele',
        ]
    },
    {
        "value": ATTACK_CLASS_SPECIFIER_VALUES['BASE_PIERCE'],
        "label": 'Pierce',
        "language_part": LANGUAGE_PART_VALUES["ATTACK_CLASS_SPECIFIER"],
        "aliases": [
            'pierce',
            'piercing',
            'range',
            'ranged',
        ]
    },
    {
        "value": ATTACK_CLASS_SPECIFIER_VALUES['CAVALRY'],
        "label": 'Cavalry',
        "language_part": LANGUAGE_PART_VALUES["ATTACK_CLASS_SPECIFIER"],
        "aliases": [
            'cavalry',
            'cav',
            'horse',
            'horses',
            'ranged',
        ]
    },
    {
        "value": ATTACK_CLASS_SPECIFIER_VALUES['INFANTRY'],
        "label": 'Infantry',
        "language_part": LANGUAGE_PART_VALUES["ATTACK_CLASS_SPECIFIER"],
        "aliases": [
            'infantry',
            'inf',
            'inft',
            'inftr',
            'ground troops',
            'swordsmen',
        ]
    },
    {
        "value": ATTACK_CLASS_SPECIFIER_VALUES['ARCHERS'],
        "label": 'Archers',
        "language_part": LANGUAGE_PART_VALUES["ATTACK_CLASS_SPECIFIER"],
        "aliases": [
            'archers',
            'archer',
            'ranged foot soldiers',
            'ranged soldiers',
        ]
    },
]

# ------ CIV ATTRIBUTES -----
# parts of speech that declare what type of attribute of a civ you are talking about
CIV_ATTRIBUTE_VALUES = {
    "CLASSIFICATION": "CLASSIFICATION",
    "BONUS": "BONUS",
    "UNIQUE_TECH": "UNIQUE_TECH",
    "UNIQUE_UNIT": "UNIQUE_UNIT",
    "REGION": "REGION",
    "ARCHITECTURE": "ARCHITECTURE",
    "EXPANSION": "EXPANSION"
}

CIV_ATTRIBUTE_SPECIFIERS = [
    {
        "value": CIV_ATTRIBUTE_VALUES["BONUS"],
        "label": 'Bonus',
        "aliases": [
            'bonus',
            'bonuses',
        ],
        "language_part": LANGUAGE_PART_VALUES["CIV_ATTRIBUTE"],
    },
    {
        "value": CIV_ATTRIBUTE_VALUES["UNIQUE_TECH"],
        "label": 'Unique Technologies',
        "aliases": [
            'unique technology',
            'unique technologies',
            'unique tech',
            'unique techs',
            'ut',
            'uts',
        ],
        "language_part": LANGUAGE_PART_VALUES["CIV_ATTRIBUTE"],
    },
    {
        "value": CIV_ATTRIBUTE_VALUES["UNIQUE_UNIT"],
        "label": 'Unique Units',
        "aliases": [
            'unique unit',
            'unique units',
            'uu',
            'uus',
        ],
        "language_part": LANGUAGE_PART_VALUES["CIV_ATTRIBUTE"],
    },
    {
        "value": CIV_ATTRIBUTE_VALUES["CLASSIFICATION"],
        "label": 'Civilization Type',
        "aliases": [
            'civ type',
            'type',
            'type of',
            'class',
            'classification',
            'focus',
            'focus of',
            'focuses',
        ],
        "language_part": LANGUAGE_PART_VALUES["CIV_ATTRIBUTE"],
    },
    {
        "value": CIV_ATTRIBUTE_VALUES["REGION"],
        "label": 'Region',
        "aliases": [
            'region',
            'area',
            'locality',
        ],
        "language_part": LANGUAGE_PART_VALUES["CIV_ATTRIBUTE"],
    },
    {
        "value": CIV_ATTRIBUTE_VALUES["ARCHITECTURE"],
        "label": 'Architecture Set',
        "aliases": [
            'architecture',
            'architecture set',
            'buildings',
            'architecture design',
            'building design',
        ],
        "language_part": LANGUAGE_PART_VALUES["CIV_ATTRIBUTE"],
    },
    {
        "value": CIV_ATTRIBUTE_VALUES["EXPANSION"],
        "label": 'Expansion',
        "aliases": [
            'expansion',
            'dlc',
        ],
        "language_part": LANGUAGE_PART_VALUES["CIV_ATTRIBUTE"],
    },

]

BONUS_SPECIFIER_VALUES = {
    "TEAM_BONUS": "TEAM_BONUS",
    "CIV_BONUS": "CIV_BONUS"
}

BONUS_SPECIFIERS = [
    {
        "language_part": LANGUAGE_PART_VALUES['BONUS_SPECIFIER'],
        "label": 'Team Bonus',
        "value": BONUS_SPECIFIER_VALUES["TEAM_BONUS"],
        "aliases": [
            "team",
            "ally"
        ],
    },
    {
        "language_part": LANGUAGE_PART_VALUES['BONUS_SPECIFIER'],
        "label": 'Civilization Bonuses',
        "value": BONUS_SPECIFIER_VALUES["CIV_BONUS"],
        "aliases": [
            "civilization",
            "civ",
        ],
    }
]

CIVILIZATION_KEYWORD_VALUE = "CIVILIZATION_KEYWORD"

CIVILIZATION_KEYWORD = [{
    "value": CIVILIZATION_KEYWORD_VALUE,
    "label": 'Civilization',
    "aliases": [
        'civ',
        'civs',
        'civilization',
        'civilizations',
        'nation',
        'nations',
        'clan',
        'clans',
        'group',
        'groups',
        'people',
        'peoples',
        'society',
        'societies',
        'culture',
        'cultures',
        'empire',
        'empires',
        'kingdom',
        'kingdoms',
    ],
    "language_part": LANGUAGE_PART_VALUES["CIVILZATION_KEYWORD"],
}]

# MODIFIERS: CIVILIZATION, TECHS (including unique techs), CIV ALLY, AGE, Attributes, specifier (upgrade, unit)

LANGUAGE_KEYWORDS = AGES + ENTITY_TYPE_SPECIFIERS + CIVILIZATIONS + CIV_ATTRIBUTE_SPECIFIERS + ENTITIES + ENTITY_ATTRIBUTES + CIVILIZATION_KEYWORD + BONUS_SPECIFIERS
# LANGUAGE_KEYWORDS = UNITS

def makeDict(language: List[dict[str, Any]]):
    language_dict = {}
    for language_element in language:
        for alias in language_element['aliases']:
            alias_first_token: str = alias.split(' ')[0]
            elements = language_dict.get(alias_first_token, [])
            entry = deepcopy(language_element)
            entry['full_alias'] = alias
            elements.append(entry)
            language_dict[alias_first_token] = elements
    return language_dict
LANGUAGE_DICTIONARY: dict[str, List[Any]] = makeDict(LANGUAGE_KEYWORDS)
